name: meetmebythebull
favicon: null
layout_spectrum: 0.8471037403214723
typography_spectrum: 0.17295282054692507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.42574281338602304
  lightness: 0.5125292311422527
  saturation: 0.5330855411011726
  rhythmicContrast: 0.13302230881527066
purpose: []
